mysql:
  enabled: false
  host: "127.0.0.1"
  port: "3306"
  database: "db"
  username: "root"
  password: ""

# settings
settings:
  token: "" #-> JDA Token
  activity: "mc.diamondcrew.cz" #-> Bot activity, will be visible.
  guild-id: 632926023637401630 #-> ID of the Guild, the bot is in.
  admin-role: 752802374979944518 #-> Admin Role ID

buy: "&eDoplÅˆky a vylepÅ¡enÃ­ zakoupÃ­te na &b<click:open_url:http://store.diamondcrew.cz>store.diamondcrew.cz</click>"

vote:
  response:
    - "Â§8â•”â•â•â•â•â•â•â•â• Â§6VOTE Â§8â•â•â•â•â•â•â•â•â•—"
    - "Â§8â•‘"
    - "Â§8â• â•<click:open_url:{url1}>Â§eCraftList &7Klik</click>"
    - "Â§8â• â•<click:open_url:{url2}>Â§eCzechCraft &7Klik</click>"
    - "Â§8â•‘"
    - "Â§8â•šâ•â•â•â•â•â•â•â• Â§6VOTE Â§8â•â•â•â•â•â•â•â•â•"

# ticket settings
tickets:
  open-category: 752811718379307092 # ID of the category for opened tickets.
  closed-category: 752811673466699810 # ID of the category, where tickets will be moved after closing.
  create-channel: 752813323573002290 #-> ID of the channel, where users can create tickets.
  create-reaction: "â“" #-> Reaction users need to add, to create a ticket.
  open-embed: #-> Embed, that will be send, after opening a ticket.
    title: "Podpora"
    description: "Ticket otevÅ™en, nynÃ­ zde prosÃ­m popiÅ¡ svÅ¯j problÃ©m."
    fields:
      - name: "Podpora tu bude co nevidÄ›t."
        value: "Pro uzavÅ™enÃ­, klikni na ğŸ”’"
  open-message: #-> List of messages, that will be sent, after opening a ticket in-game.
    - "Â§8â•”â•â•â•â•â•â•â•â• Â§aTICKET Â§8â•â•â•â•â•â•â•â•â•—"
    - "Â§8â•‘"
    - "Â§8â• â•Â§bÂ§l {userName}"
    - "Â§8â•‘ Â§f{url}"
    - "Â§8â•‘"
    - "Â§8â•šâ•â•â•â•â•â•â•â• Â§aTICKET Â§8â•â•â•â•â•â•â•â•â•"
  close-emote: "ğŸ”’"

# roles
roles:
  PREMIUM:
    perm: "discord.group.premium"
    role: 752814579507134505
  YOUTUBE:
    perm: "discord.group.youtube"
    role: 712386306839150642
  TWITCH:
    perm: "discord.group.twitch"
    role: 782269399938891787
  TESTER:
    perm: "discord.group.tester"
    role: 649628473845088293
  BUILD:
    perm: "discord.group.build"
    role: 642097528510218270
  MOD:
    perm: "discord.group.mod"
    role: 642097646735065109
  ADMIN:
    perm: "discord.group.admin"
    role: 642098109857529866
  DEV:
    perm: "discord.group.dev"
    role: 642097433488392227
  HEADMOD:
    perm: "discord.group.headmod"
    role: 698966784283246592
  HEADBUILD:
    perm: "discord.group.headbuild"
    role: 642097815551475739
  HEADADMIN:
    perm: "discord.group.headbuild"
    role: 698967921539547166
  DISCORD_ADMIN:
    perm: "discord.admin"
    role: 752802374979944518

# react for role
react:
  confirm:
    channel: 752812808034582549
    emote: "ALL"
    role: 752842207031197746
  frakce:
    channel: 752813365771894804
    emote: "1ï¸âƒ£"
    role: 752815962335739952
  uhc:
    channel: 752813365771894804
    emote: "2ï¸âƒ£"
    role: 755201759579865129
  bedwars:
    channel: 752813365771894804
    emote: "3ï¸âƒ£"
    role: 773544187470938112
  buildbattle:
    channel: 752813365771894804
    emote: "4ï¸âƒ£"
    role: 781056260920311809

# simple commands
simple-commands:
  banlist:
    aliases: ["ban", "bans", "zabanovani"]
    embed:
      title: "Seznam ZabanovanÃ½ch"
      description: "https://mc.diamondcrew.cz/bans"
  discord:
    aliases: ["link", "invite"]
    embed:
      title: "Discord PozvÃ¡nka"
      description: "https://mc.diamondcrew.cz/discord"
  info:
    aliases: ["help", "pomoc"]
    embed:
      title: "NÃ¡povÄ›da"
      description: "ZÃ¡kladnÃ­ pomÅ¯cka pro hrÃ¡Äe DiamondCrewMC."
      fields:
        1:
          name: "WebovÃ¡ StrÃ¡nka"
          value: "http://mc.diamondcrew.cz"
        2:
          name: "Obchod"
          value: "http://store.diamondcrew.cz"
        3:
          name: "Discord Link"
          value: "http://mc.diamondcrew.cz/discord"
        4:
          name: "Wiki"
          value: "http://wiki.diamondcrew.cz"
        empty1: []
        5:
          name: "NÃ¡bor"
          value: "MÃ¡te-li zÃ¡jem stÃ¡t se Älenem/kou naÅ¡eho tÃ½mu, vytvoÅ™te si ticket v mÃ­stnosti #â“podpora"
        6:
          name: "Minecraft Server"
          value: "`play.diamondcrew.cz` | `mc.diamondcrew.cz`"
        7:
          name: "TeamSpeak 3 Server"
          value: "`play.diamondcrew.cz`"
        8:
          name: "NaÅ¡li jte chybu, nebo mÃ¡te jinÃ½ druh problÃ©mu?"
          value: "ObrtaÅ¥te se do mÃ­stnosti #â“podpora a vytvoÅ™te si ticket."
        9:
          name: "Chcete dostÃ¡vat informace o vÃ½voji jednotlivÃ½ch serverÅ¯ a zapojit se do komunitnÃ­ch akcÃ­?"
          value: "PÅ™ejdÄ›te do mÃ­stnosti #ğŸ™‹role a vyberte si servery, kterÃ© VÃ¡s zajÃ­majÃ­."
    ip:
      aliases: ["serverip", "ipserver"]
      embed:
        title: "IP Adresa (MC & TS3)"
        description: "play.diamondcrew.cz"
    rules:
      aliases: ["pravidla"]
      embed:
        title: "Pravidla"
        description: "http://wiki.diamondcrew.cz"
    store:
      aliases: ["shop", "obchod", "premium", "vip"]
      embed:
        title: "Obchod"
        description: "http://store.diamondcrew.cz"
    webpage:
      aliases: ["web", "website", "stranka", "stranky"]
      embed:
        title: "WebovÃ¡ StrÃ¡nka"
        description: "http://mc.diamondcrew.cz"
    youtube:
      aliases: ["yt", "twitch", "stream"]
      embed:
        title: "YouTube/Twitch Program"
        description: "Informace o partnerskÃ©m YouTube/Twitch programu."
        fields:
          1:
            name: "PodmÃ­nky"
            value: "> PodmÃ­nky pro pÅ™ijetÃ­ do naÅ¡eho programu jsou velmi struÄnÃ© a jasnÃ©.
                    - AktivnÄ› vydÃ¡vat/streamovat obsah, souvisejÃ­cÃ­ s Minecraftem na VaÅ¡em kanÃ¡le.
                    - Streamovat alespoÅˆ jednou z *DCMC* serverÅ¯, v urÄenÃ© dobÄ›.
                    - StreamovanÃ½ obsah z naÅ¡ich serverÅ¯, nesmÃ­ poruÅ¡ovat Å¾Ã¡dnÃ© z jeho pravidel."
          2:
            name: "Co mÅ¯Å¾eme nabÃ­dnout"
            value: "> VaÅ¡e benefity, ze zapojenÃ­ v naÅ¡em programu, nejsou absolutnÃ­, aktivnÄ› se snaÅ¾Ã­me pÅ™idÃ¡vat vÃ­ce.
                    > ZaroveÅ„ je moÅ¾nost speciÃ¡lnÃ­ch benefitÅ¯ na VaÅ¡i osobu, po domluvÄ›.
                    - HernÃ­ **YT/Twitch** hodnost, na vÅ¡ech serverech, obsahujÃ­cÃ­ vÅ¡echny(+bonusovÃ©) vÃ½hody *Premium* hodnosti.
                    - VÃ¡Å¡ kanÃ¡l bude pÅ™idÃ¡n do seznamu na webu a vÅ¡ech hlavnÃ­ch hernÃ­ch lobby.
                    - Po bliÅ¾Å¡Ã­ dohodÄ› mÅ¯Å¾eme nabÃ­dnou vlastnÃ­ *Minecraft Server* pro VÃ¡s a VaÅ¡e publikum."
        footer:
          name: "V pÅ™Ã­padÄ› zÃ¡jmu o vstoupenÃ­ do vÃ½Å¡e uvedenÃ©ho programu a splnÄ›nÃ­ poÅ¾adavkÅ¯, vÄ›Å™Ã­me Å¾e se oboum stranÃ¡m otevÅ™e spousta pÅ™Ã­leÅ¾itostÃ­ k prosperovÃ¡nÃ­ z krÃ¡tkodobÃ©ho i dlouhodobÃ©ho hlediska a budeme se tÄ›Å¡it na vzÃ¡jemnou spoluprÃ¡ci."
    ytserver:
      aliases: ["vlastniserver"]
      embed:
        title: "VlastnÃ­ Minecraft Server"
        description: "Informace o vlastnÃ­m Minecraft Serveru."
        fields:
          1:
            name: "VlastnÃ­ Minecraft Server"
            value: "> Pokud si zaÅ¾Ã¡dÃ¡te o vlastnÃ­ server pro VaÅ¡e sledujÃ­cÃ­ a VaÅ¡e Å¾Ã¡dost bude schvÃ¡lena, budete mÃ­t pÅ™Ã­stup k tÄ›mto benefitÅ¯m.
                    *PrvotnÃ­ nastavenÃ­ serveru*
                    - MoÅ¾nost vÃ½bÄ›ru verze od **1.8.x** a vÃ½Å¡e.
                    - MoÅ¾nost zmÄ›ny vÅ¡ech nastavenÃ­ serveru, kromÄ› `online-mode`. (VÅ¾dy `false`)"
          2:
            name: "PÅ™enesenÃ© vÃ½hody, pÅ™i pÅ™ipojenÃ­ k naÅ¡emu networku"
            value: "- AutomatickÃ© pÅ™ihlÃ¡Å¡enÃ­ pro originÃ¡lnÃ­ uÅ¾ivatele.
                    - AutomatickÃ© pÅ™ihlÃ¡Å¡enÃ­ po zvolenou dobu pro ne-origionÃ¡lnÃ­ uÅ¾ivatele.
                    - V pÅ™ipadÄ› zmÄ›ny nicku originÃ¡lnÃ­ho uÅ¾ivatele, vÅ¡echny data budou automaticky pÅ™eneseny.
                    - DDoS, Bot a Spoof ochrana."
          3:
            name: "OstatnÃ­ benefity serveru"
            value: "- Server bude z VaÅ¡Ã­ strany zcela zdarma
                    - Na server se budete moci pÅ™ipojit z hlavnÃ­ch hernÃ­ch lobby.
                    - MoÅ¾nost nastavenÃ­ vCPU a RAM, podle bliÅ¾Å¡Ã­ dohody.
                    - O server se bude starat nÃ¡Å¡ tÃ½m profesionÃ¡lnÃ­ch vÃ½vojÃ¡Å™Å¯, s dlouholetÃ½mi zkuÅ¡enostmi.
                    - V pÅ™Ã­padÄ› potÅ™eby na server budou pÅ™Ã­dÃ¡ny pluginy, dle VaÅ¡ich pÅ™edstav a poÅ¾adavkÅ¯, zÃ¡roveÅˆ je moÅ¾nost vytvoÅ™enÃ­ vlastnÃ­ch.
                    - Budete mÃ­t kompletnÃ­ pÅ™Ã­stup k zÃ¡kladnÃ­m funkcÃ­m serveru, v prostÅ™edÃ­ modernÃ­ho panelu."


